name: qr_code_scanner_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # scan QR Code
  flutter_barcode_scanner: ^1.0.1

  # create QR Code
  barcode_widget: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true